# Generated by Django 4.1.3 on 2022-11-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='datetime',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2023-01-01', verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='12:00', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(choices=[('Seattle', 'Seattle'), ('Los Angeles', 'Los Angeles'), ('San Francisco', 'San Francisco')], default='Seattle', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='neighborhood',
            field=models.CharField(choices=[('Queen Anne', 'Queen Anne'), ('Capitol Hill', 'Capitol Hill'), ('Downtown', 'Downtown'), ('Belltown', 'Belltown'), ('West Seattle', 'West Seattle'), ('Ballard', 'Ballard'), ('Fremont', 'Fremont'), ('South Lake Union', 'South Lake Union'), ('University District', 'University District'), ('Pioneer Square', 'Pioneer Square'), ('International District', 'International District'), ('Eastlake', 'Eastlake')], default='Queen Anne', max_length=50),
        ),
    ]
